print('='*57)
print('abcd'*80)
nome = input('Seu nome: ')
print('Prazer em conhecê-lo {:>50}.'.format(nome))
print('Prazer em conhecê-lo {:>40}.'.format(nome))
print('Prazer em conhecê-lo {:>30}.'.format(nome))
print('Prazer em conhecê-lo {:>20}.'.format(nome))
print('Prazer em conhecê-lo {:>10}.'.format(nome))
print('Prazer em conhecê-lo {}.'.format(nome))
print('Prazer em conhecê-lo {:<10}.'.format(nome))
print('Prazer em conhecê-lo {:<20}.'.format(nome))
print('Prazer em conhecê-lo {:<30}.'.format(nome))
print('Prazer em conhecê-lo {:<40}.'.format(nome))
print('Prazer em conhecê-lo {:<50}.'.format(nome))
print('Prazer em conhecê-lo {:^10}.'.format(nome))
print('Prazer em conhecê-lo {:^20}.'.format(nome))
print('Prazer em conhecê-lo {:^30}.'.format(nome))
print('Prazer em conhecê-lo {:^40}.'.format(nome))
print('Prazer em conhecê-lo {:^50}.'.format(nome))
print('Prazer em conhecê-lo {:=^10}.'.format(nome))
print('Prazer em conhecê-lo {:=^20}.'.format(nome))
print('Prazer em conhecê-lo {:=^30}.'.format(nome))
print('Prazer em conhecê-lo {:=^40}.'.format(nome))
print('Prazer em conhecê-lo {:=^50}.'.format(nome))

